name: Dev Pull request checker

on: pull_request

jobs:
  test-project:

    runs-on: macos-latest
  
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - name: Download XCBeautify 0.9.1
      run: |
        curl -L -o xcbeautify-0.9.1.zip https://github.com/thii/xcbeautify/releases/download/0.9.1/xcbeautify-0.9.1-x86_64-apple-macosx.zip
        unzip -qq ./xcbeautify-0.9.1.zip

    - name: Build and test
      run: |
        set -o pipefail
        xcodebuild -project 'StackOv.xcodeproj' \
          -scheme 'StackOv (iOS)' \
          -sdk iphonesimulator \
          -destination platform='iOS Simulator,name=iPhone 12,OS=14.2' \
          -derivedDataPath .build/derivedData \
          test \
          | ./xcbeautify
    
    - name: Upload coverage to Codecov
      run: bash <(curl -s https://codecov.io/bash) -D .build/derivedData
    
